version: "3.7"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DJANGO_DATABASE_USER}
      - POSTGRES_PASSWORD=${DJANGO_DATABASE_PASSWORD}
      - POSTGRES_DB=${DJANGO_DATABASE_NAME}
    env_file:
        - .env
    ports:
      - "5432:5432"
  app:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py model_datas &&
             python manage.py test &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis
      - listener
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  redis:
    image: redis:latest
    expose:
      - '6379'
    ports:
      - "6379:6379"
  listener:
    build: listener
    command: >
      sh -c "python listener.py"
    depends_on:
      - redis
    links:
      - redis

